name: cubit
description: A Flutter library built to expose widgets that integrate with cubits. Built to work with the cubit and bloc state management packages.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.3
  meta: ^1.1.8

